CC = gcc
CFLAGS = -O2 -march=native -pipe
CFLAGS += -I/usr/include/libdrm -I/usr/include/libkms -I/usr/include/freetype2
LDFLAGS = -s
LDFLAGS += -lpthread -lutil -ldrm -lkms -lfreetype

# Set to path for the libteken include files
LIBTEKEN_CFLAGS = -I/usr/local/include

# Set path for the libteken library
LIBTEKEN_LDFLAGS = -lteken -L/usr/local/lib -Wl,-rpath=/usr/local/lib

CFLAGS += ${LIBTEKEN_CFLAGS}
LDFLAGS += ${LIBTEKEN_LDFLAGS}

OBJECTS = fbteken.o rop32.o

all: fbteken

fbteken: $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

.c.o:
	$(CC) -c $(CFLAGS) $<

clean:
	rm -f fbteken $(OBJECTS)

.PHONY: clean
